openapi: 3.0.3
info:
  title: STD24041
  description: "This is a specification of STD24041"
  version: "1.0.0"

servers:
  - url: http://localhost:8000

paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Retourne le texte "Ok"
          content:
            text/plain:
              schema:
                type: string
                example: Ok

  /phones:
    post:
      description: Créer un nouveau téléphone
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Phone"
      responses:
        '201':
          description: Téléphone créé avec succès
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Phone"

    get:
      summary: Récupérer la liste des téléphones
      responses:
        '200':
          description: Liste de téléphones
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Phone"

  /phones/{id}:
    get:
      summary: Récupérer un téléphone par son identifiant
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Téléphone trouvé
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Phone"
        '404':
          description: Téléphone non trouvé
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "Phone with id p1 not found"

components:
  schemas:
    Characteristic:
      type: object
      properties:
        ram_memory:
          type: integer
          example: 8
        rom_memory:
          type: integer
          example: 128
      required:
        - ram_memory
        - rom_memory

    Phone:
      type: object
      properties:
        identifier:
          type: string
          example: "p1"
        brand:
          type: string
          example: "Samsung"
        model:
          type: string
          example: "S21"
        characteristics:
          $ref: "#/components/schemas/Characteristic"
      required:
        - identifier
        - brand
        - model
        - characteristics
